### ISSUE TITLE
CoreDNS timing out on DNS Queries on EKS built using RedHat 8.9

### ISSUE THREAD

**Issue by hectoralicea** [aws-samples/amazon-eks-ami-rhel#2]
I ran the following make to build a RHEL based EKS Node AMI
```
make k8s=1.28 source_ami_filter_name=RHEL-8.9.0_HVM-2023*-x86_64-* ami_regions=us-gov-west-1 aws_region=us-gov-west-1
```
with updated eks-worker-rhel-variables.json with my vpc-id and subnet-id to launch and ami the EC2 

The cluster built fine, but for some reason some of the utility pods fail, specifically coredns, ebs-csi-controller, and ebs-csi-node.  It appears the root cause may be a CoreDNS issue.

Any pointers at what to look at to figure out why the cluster after initial boot is not able to reach my DNS?  I have another cluster running based on Amazon Linux out of the box EKS AMI that works just fine.  I actually tore down this cluster, rebuilt with the default Amazon Linux EKS AMI and it worked fine.  Then I tore that down and rebuilt using the RHEL8 EKS AMI and I got the same issue, therefore its not an infrastructure issue outside of the cluster.

Following is the log:
``` 
hector$ kc logs -n kube-system   coredns-7df9ff6644-7c8j4 -f
[INFO] plugin/kubernetes: waiting for Kubernetes API before starting server
[INFO] plugin/kubernetes: waiting for Kubernetes API before starting server
[INFO] plugin/kubernetes: waiting for Kubernetes API before starting server
[INFO] plugin/kubernetes: waiting for Kubernetes API before starting server
[INFO] plugin/kubernetes: waiting for Kubernetes API before starting server
[INFO] plugin/kubernetes: waiting for Kubernetes API before starting server
[INFO] plugin/kubernetes: waiting for Kubernetes API before starting server
[INFO] plugin/kubernetes: waiting for Kubernetes API before starting server
[INFO] plugin/kubernetes: waiting for Kubernetes API before starting server
[WARNING] plugin/kubernetes: starting server with unsynced Kubernetes API
.:53
[INFO] plugin/reload: Running configuration SHA512 = 8a7d59126e7f114ab49c6d2613be93d8ef7d408af8ee61a710210843dc409f03133727e38f64469d9bb180f396c84ebf48a42bde3b3769730865ca9df5eb281c
CoreDNS-1.10.1
linux/amd64, go1.20.4, 84446ec6
[ERROR] plugin/errors: 2 971496681973262690.8383050482943311004. HINFO: read udp 10.0.12.18:43298->10.20.4.10:53: i/o timeout
[ERROR] plugin/errors: 2 971496681973262690.8383050482943311004. HINFO: read udp 10.0.12.18:56992->10.20.3.10:53: i/o timeout
[ERROR] plugin/errors: 2 971496681973262690.8383050482943311004. HINFO: read udp 10.0.12.18:41932->10.20.4.10:53: i/o timeout
[ERROR] plugin/errors: 2 971496681973262690.8383050482943311004. HINFO: read udp 10.0.12.18:40445->10.20.3.10:53: i/o timeout
[ERROR] plugin/errors: 2 971496681973262690.8383050482943311004. HINFO: read udp 10.0.12.18:54652->10.20.3.10:53: i/o timeout
[ERROR] plugin/errors: 2 971496681973262690.8383050482943311004. HINFO: read udp 10.0.12.18:52491->10.20.3.10:53: i/o timeout
[ERROR] plugin/errors: 2 971496681973262690.8383050482943311004. HINFO: read udp 10.0.12.18:32808->10.20.4.10:53: i/o timeout
[ERROR] plugin/errors: 2 971496681973262690.8383050482943311004. HINFO: read udp 10.0.12.18:57138->10.20.3.10:53: i/o timeout
[ERROR] plugin/errors: 2 971496681973262690.8383050482943311004. HINFO: read udp 10.0.12.18:53433->10.20.4.10:53: i/o timeout
[ERROR] plugin/errors: 2 971496681973262690.8383050482943311004. HINFO: read udp 10.0.12.18:38944->10.20.3.10:53: i/o timeout
[INFO] SIGTERM: Shutting down servers then terminating
[INFO] plugin/health: Going into lameduck mode for 5s
```

**Comment by bradwatsonaws** [comment]
Hi @hectoralicea ! This is likely due to a known issue with the Red Hat nm-cloud-setup service. Check out this [blog](https://aws.amazon.com/blogs/containers/run-amazon-eks-on-rhel-worker-nodes-with-ipvs-networking/), which makes mention of this issue at the bottom of the Introduction section. There is a [Red Hat KB article](https://access.redhat.com/solutions/6319811) for this.

To get past this issue and get CoreDNS operational - disable the nm-cloud-setup service and timer and reboot your EC2 Instance during your worker node bootstrapping process (User Data script).

Check out lines 41-43 in the [create_nodegroup.sh](https://github.com/aws-samples/amazon-eks-ami-rhel/blob/main/create_nodegroup.sh) script of this repo, which do this.

User Data from create_nodegroup.sh script:

```shell
#!/bin/bash
/etc/eks/bootstrap.sh $EKS_CLUSTER --container-runtime containerd
systemctl disable nm-cloud-setup.timer
systemctl disable nm-cloud-setup.service
reboot
```

For what it's worth - I tried numerous times to add these commands to the bottom of the install-worker.sh script, but I could never get worker nodes to join the cluster when doing so. It led me to believe this service was necessary during EC2 Instance launch but could be disabled after startup. Bit of a "chicken/egg" scenario...

**Comment by hectoralicea** [comment]
wow, this is great info.  A very rainy day in the east coast, so I'll be devouring this information and testing this out.  Thanks

**Comment by bradwatsonaws** [comment]
East coast here as well so feeling the pain. Keep me posted!

**Comment by hectoralicea** [comment]
Ok, reviewing this code, `create_nodegroup.sh`, and it appears this is for EKS provisioning after the AMI creation, and it's actually the `overrideBootstrapCommand` for "a" (not sure which) EKS to be provisioned.  

So I suspect I need to put that in my own  `overrideBootstrapCommand` for my own call to `eksctl` to provision my EKS.  Is that correct?

**Comment by bradwatsonaws** [comment]
Correct. That script is for use with eksctl. If you are using an EC2 Launch Template instead of eksctl, you would just include those commands in the User Data portion of your Launch Template.
After creating about 25 launch templates manually during testing I decided to write that create_nodegroup.sh script and leverage eksctl.

**Comment by bradwatsonaws** [comment]
In the blog I linked above - there are instructions for using that create_nodegroup.sh script. Here they are:

```shell
./create_nodegroup.sh <CLUSTER_NAME> <AMI_ID> <NODE_GROUP_NAME> <REGION> <KEY_PAIR> <INSTANCE_TYPE> <MIN_GROUP_SIZE> <DESIRED_GROUP_SIZE> <MAX_GROUP_SIZE>
``` 

Example:
```shell
./create_nodegroup.sh rhel-cluster ami-0c6d588be9ce412ef rhelnodegroup us-gov-east-1 govcloudkeypair t3.large 5 5 5
```

**Comment by hectoralicea** [comment]
adding the below to my  overrideBootstrapCommand and rerunning eksclt to create the cluster worked.  Am continuing testing but so far so good
```
/etc/eks/bootstrap.sh $EKS_CLUSTER
systemctl disable nm-cloud-setup.timer
systemctl disable nm-cloud-setup.service
reboot
```

**Comment by hectoralicea** [comment]
the above worked.  closing this ticket.

**Comment by hectoralicea** [comment]
the above worked. closing this ticket.
